### ISSUE TITLE
Add variable expansion in the service configuration file

### ISSUE THREAD

**Issue by jpbelanger-mtl** [jpbelanger-mtl/kube-pod-decorator#1]
Add some simple variable expansion in the configuration file. One use-case is the ability to fetch consul/vault KV based on the current environment. All environment variable passed to the container would be available in the configuration file.

```
vault:
  - name: myDBSecret
    type: database
    path: database-{{ environment }}/creds/readonly
consul:
  - name: myConsulValue
    path: config/{{ environment }}/cluster-info
    type: json
```
